version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: techchallenge-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techchallengefase3
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - techchallenge-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: techchallenge-rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672" 
    networks:
      - techchallenge-net

  agendamento-service:
    build: ./agendamento-service
    container_name: agendamento-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/techchallengefase3?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - mysql     
      - rabbitmq
    networks:
      - techchallenge-net

  notificacoes-service:
    build: ./notificacoes-service
    container_name: notificacoes-service
    ports:
      - "8081:8081"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - rabbitmq
    networks:
      - techchallenge-net

networks:
  techchallenge-net:
    driver: bridge

volumes:
  mysql-data: